version: '3.8'

services:
  git-cloner:
    image: alpine/git:latest
    container_name: yt-dlp-git-cloner
    volumes:
      - app-source:/git-data
    entrypoint: ""
    command: >
      sh -c "
        if [ ! -d /git-data/.git ]; then
          echo 'Cloning repository...'
          git clone https://github.com/NCLC-AI/yt-dlp-server.git /git-data
        else
          echo 'Repository exists, pulling latest changes...'
          cd /git-data && git pull origin main
        fi &&
        echo 'Git operation completed successfully'
      "

  yt-dlp-server:
    image: n8nai/yt-dlp-server:latest
    container_name: yt-dlp-server
    restart: always
    depends_on:
      git-cloner:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    volumes:
      - app-source:/app/source
      # /tmp은 컨테이너 내부에서 자동으로 정리되므로 별도 볼륨 불필요
    environment:
      - PORT=5000
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/source
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app-source:
    driver: local
